### ISSUE TITLE
GDPR Implementation

### ISSUE THREAD

**Issue by nashtechdev01** [maths/moodle-qbehaviour_adaptivemultipart#3]
Hi @sangwinc,
Our clients are using this theme and implement GDPR for other plugin. Do you have plan to implement GDPR in the future for this plugin ?
If you don't have any plan to implement it, can we create a pull request to implement it ?

**Comment by sangwinc** [comment]
What do you suggest needs doing here?

**Comment by nashtechdev01** [comment]
Hi @sangwinc,
I checked the plugin, it does not contain personal data, it should be implemented the null_provider.
If we don't, in the "Plugin privacy registry", a warning icon is displayed on this plugin.
How about you opinion ? Can we create a pull request to implement it ?

**Comment by sangwinc** [comment]
If you know what to do, please do send me a pull request and I'll review it.  Thanks!
Chris

**Comment by nashtechdev01** [comment]
The gdpr is implemented, this issue is closed.
